In [2]:
import torch
torch.__version__

'1.11.0'

In [3]:
x = torch.rand(10)
print(x)
print(x.size())

tensor([0.9528, 0.1660, 0.7781, 0.8001, 0.5604, 0.1106, 0.3404, 0.4946, 0.5892,
        0.1310])
torch.Size([10])


In [4]:
temp = torch.FloatTensor([23, 24, 24.5, 26, 27, 27.2, 23.0])
print(temp.size())
print(temp.dtype)
print(temp)

torch.Size([7])
torch.float32
tensor([23.0000, 24.0000, 24.5000, 26.0000, 27.0000, 27.2000, 23.0000])


In [5]:
x = torch.ones((2, 2), requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [6]:
print(x.data)

tensor([[1., 1.],
        [1., 1.]])


In [7]:
print(x.grad)

None


In [8]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [9]:
print(y.grad_fn)

In [10]:
z = y * y * 3
out = z.mean()

In [14]:
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [18]:
a = torch.randn((2, 2))
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad = True
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [19]:
out.backward()
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [20]:
print(x.requires_grad)

True


In [21]:
print((x**2).requires_grad)

True


In [23]:
with torch.no_grad():
    print((x**2).requires_grad)

False
